### PR TITLE
bump ngrok

### PR DESCRIPTION
**Pull request by nkzawa**
This PR will fix https://github.com/rase-/zuul-ngrok/pull/7 .
I think we have to merge https://github.com/rase-/zuul-ngrok/pull/8 for environment variable support.

### CODE REVIEW

**Comment by nkzawa** [comment]
Umm, some tests still fail even with this fix. https://travis-ci.org/socketio/engine.io-client/builds/81337562

**Comment by cristiandouce** [comment]
Nice @nkzawa !
This one and #8 are better fit than my #7 :dancers:

**Comment by vvo** [comment]
So are we good now? Merge and release? :)

**Comment by nkzawa** [comment]
I found that the reason of our test failures is that ngrok v2 has limitation of "1 online client".
This PR will be OK. Can you check please, @rase- ?

**Comment by vvo** [comment]
So you can have only one tunnel at a time?

**Comment by nkzawa** [comment]
Yes, I believe so. See https://ngrok.com/product
I asked the ngrok author about it and confirmed the limitation was added on v2.

**Comment by cristiandouce** [comment]
@nkzawa It's been a week since your update proposal. Would you mind sharing a tag in your fork with your changes so we can rely on a more or less stable source for this?

Thanks!!

**Comment by rase-** [comment]
Thanks!

**Pull request merged**
